### ISSUE TITLE
How to migrate to Dialogflow API V2 and the v2 client library for android client?

### ISSUE THREAD

**Issue by YinXiuYu** [dialogflow/dialogflow-android-client#111]
Dear Google:
I noticed that Dialogflow client library and Dialogflow API V1 have been deprecated and will be shut down on October 23th, 2019, so want to migrate to v2 client library , however, the Java client document mentions the following : “To install the client library: Caution:The Java client library does not support Android.”  
How to migrate to Dialogflow API V2 and the v2 client library for android client?
Looking forward to your answer, thanks a lot advance!

**Comment by realill** [comment]
Do not use this old lib. Use dialogflow cloud library.

**Comment by YinXiuYu** [comment]
Dear realill ,thanks for your answer, You mean I can use the Dialogflow API V2 within an android app. Can you say more specifically, or can you share an example? Thanks a lot advance!

**Comment by realill** [comment]
You should be able to use this Java library to build for Android
https://cloud.google.com/dialogflow/docs/reference/libraries/java

But it is quite different from this old one.

**Comment by YinXiuYu** [comment]
Dear realill, 
 Thanks for your reply , but the Java client document mentions the following : “To install the client library: Caution:The Java client library does not support Android.”
So I want to know what the Dialogflow’s support plan is for used within the Android app. Could you please help us confirm this ? Thanks  a lot advance!

**Comment by prb407** [comment]
@realill How can we migrate from v1 to v2 for the client library?

**Comment by lelele3kimo** [comment]
Dear all,
The following case shows the difference of calling dialogflow API V1 and V2 library.
https://github.com/abhi007tyagi/DialogflowChat

**Comment by vinayjoglekar** [comment]
@lelele3kimo java client library does not work with firestore library and it is not recommended in android.
Is there any other way around?

**Comment by lelele3kimo** [comment]
@vinayjoglekar Sorry, I don't know how to let java client library work with firestore library. My post only provided an example to show how to migrate V1 to V2 for dialogflow android client.

**Comment by vikasrairajput** [comment]
@vinayjoglekar  I m facing the same issue already spent 3 days looking for a solution. Do you found any solution? dialogflow and firestore not working together.

**Comment by SanthoshMKunthe** [comment]
How to integrate Dialogflow v2 or dialogflow in general into Java/Kotlin android app.

I dont want to use https://medium.com/@abhi007tyagi/android-chatbot-with-dialogflow-8c0dcc8d8018 or https://github.com/abhi007tyagi/DialogflowChat . . .

**Comment by vicianm** [comment]
Hi, we created an [Android Dialogflow v2 client library](https://github.com/Educards/android-dialogflow), which uses the official [Google Cloud Java lib](https://cloud.google.com/dialogflow/es/docs/reference/libraries/java) to communicate with Dialogflow.
