### ISSUE TITLE
URLs to be allowed when using dialogflow-android in restricted network. . .

### ISSUE THREAD

**Issue by SanthoshMKunthe** [dialogflow/dialogflow-android-client#114]
I am using dialogflow integrated android-application in restricted-internet environment. . . Can some one give me a list of URLs that I need to WHITELIST so that the application's dialogflow part has access to internet inside restricted-internet environment. . . I completely understand that this information can't be shared, but this is something much required by many people who are security conscious. . .

**Comment by realill** [comment]
I do not have list of URLS, but I can give you some advice:
1) APIs are open, you can probably find URLs in docs https://cloud.google.com/dialogflow/docs/reference/rest/v2-overview, depending on what version of protocol you are using.
2) When you issue query from Dialogflow console, there is Copy Curl button there, it contains URL.
3) If you use client library, you can probably find urls in source code, I think all dialogflow libraries are opensourced.
4) You can try to use network sniffer to sniff URLs out. For instance you can install one on your laptop and run your app in android emulator on your laptop.
