### ISSUE TITLE
How to get all the text response?

### ISSUE THREAD

**Issue by divyanshub024** [dialogflow/dialogflow-android-client#42]
In Android SDK I'm getting response like this-

final Result result = response.getResult();
final String speech = result.getFulfillment().getSpeech();
Log.i(TAG, "Speech: " + speech);

This will give only one response. How can I get all the text responses?
Please help me out?

**Comment by AniFichadia** [comment]
Use `response.getFulfillment().getMessages()` instead. You can iterate through the items and use an instanceof check against `ResponseSpeech` class. You can refer to the  `ai.api.model.ResponseMessage` class for other sub types (like Quick replies etc)

**Comment by rahmansaleh** [comment]
> Use `response.getResults().getFulfillment().getMessages()` instead. You can iterate through the items and use an instanceof check against the `ResponseSpeech` class. Refer to the `ai.api.model.ResponseMessage` class for other sub types (like Quick replies etc).
> 
> I only use `response.getResults().getFulfillment().getSpeech()` as a fallback if nothing else comes in messages

Sir. can you explain more detailed step-by-step ? please.. i so glad can found your explain but i can understand it. thanks so much

**Comment by nasirhasanov** [comment]
> Use `response.getResults().getFulfillment().getMessages()` instead. You can iterate through the items and use an instanceof check against the `ResponseSpeech` class. Refer to the `ai.api.model.ResponseMessage` class for other sub types (like Quick replies etc).
> 
> I only use `response.getResults().getFulfillment().getSpeech()` as a fallback if nothing else comes in messages

Sir.  What can I get custom payload from ResponseMessage ?

**Comment by vaibhavs2** [comment]
`for (int i = 0; i < messageCount; i++) {
                        ResponseMessage.ResponseSpeech responseMessage = (ResponseMessage.ResponseSpeech) response.getResult().getFulfillment().getMessages().get(i);
                        Log.e(TAG, "responseMessage: " + responseMessage.getSpeech().toString());

                        reply=responseMessage.getSpeech().toString().replaceAll(regexSquare,"");
                        ChatMessage chatMessage = new ChatMessage(reply, "bot");
                        mDatabase.child("chat").child(UserId).push().setValue(chatMessage);
                       // showTextView(responseMessage.getSpeech().get(0), BOT);
                    }`


I am getting this Error 

_E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.victoria, PID: 2716
    java.lang.ClassCastException: ai.api.model.GoogleAssistantResponseMessages$ResponseChatBubble cannot be cast to ai.api.model.ResponseMessage$ResponseSpeech_


How to solve this? please!

**Comment by vaibhavs2** [comment]
` for (int i = 0; i < messageCount; i++) {
ResponseMessage.ResponseSpeech responseMessage = (ResponseMessage.ResponseSpeech) response.getResult().getFulfillment().getMessages().get(i);
Log.e(TAG, "responseMessage: " + responseMessage.getSpeech().toString());

                    reply=responseMessage.getSpeech().toString().replaceAll(regexSquare,"");
                    ChatMessage chatMessage = new ChatMessage(reply, "bot");
                    mDatabase.child("chat").child(UserId).push().setValue(chatMessage);
                   // showTextView(responseMessage.getSpeech().get(0), BOT);
                } `
I am getting this Error

_E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.victoria, PID: 2716
java.lang.ClassCastException: ai.api.model.GoogleAssistantResponseMessages$ResponseChatBubble cannot be cast to ai.api.model.ResponseMessage$ResponseSpeech_

How to solve this? please!
