### ISSUE TITLE
2.0.7@aar missing SupportedLanguages enum

### ISSUE THREAD

**Issue by cuchas** [dialogflow/dialogflow-android-client#68]
Hi, I've imported ai.api:sdk:2.0.7@aar and tried to use it but the AIConfiguration.SupportedLanguages enum is missing, what version should I use till the fix?

**Comment by ourdex86** [comment]
Any update ? Even I am trying to use the same. Couldn't find `AIConfiguration.SupportedLanguages.English`

**Comment by Abdulr-intija** [comment]
Yeah, same issue over here too. It seems like it has been removed from 2.0.7 so i used 1.9.0 and it worked well. So instead of importing ai.api:sdk:2.0.7@aar , i imported ai.api:sdk:1.9.0@aar

**Comment by cuchas** [comment]
I've checked another issues and found the SupportedLanguages remains at 'ai.api:libai:1.6.12', so I added it together with sdk 'ai.api:sdk:2.0.7@aar' and it worked!

**Comment by Danm72** [comment]
Unbelievable that this is still open
